public enum GameEvent
{
    COLLECTIBLE_EARNED,

    OBJECTIVES_INITIALIZED,
    OBJECTIVE_COMPLETED,
    OBJECTIVE_FAILED,

    LEVEL_COMPLETED,
    LEVEL_FAILED,
    LEVEL_STARTED,

    CURRENT_WORLD_CHANGED,


    // Element and Grid Events
    ELEMENT_SELECTED,
    ELEMENT_MATCHED,
    ELEMENT_DESTROYED,
    ELEMENTS_SWAPPED,
    SWAP_FAILED,
    MATCH_DETECTED,
    COMBO_TRIGGERED,
    GRAVITY_STARTED,
    GRAVITY_COMPLETED,
    ELEMENTS_REFILLED,
    GRID_INITIALIZED,
    GRID_STABLE,
    
    // Currency Events
    CURRENCY_EARNED,
    CURRENCY_SPENT,
    
    // Action Bar Events
    ACTION_USED,
    ACTION_CLICKED,
    
    // UI Events
    SCREEN_OPENED,
    SCREEN_CLOSED,
    
    // Special Elements
    BOX_DESTROYED,
    SPECIAL_ELEMENT_ACTIVATED,
    BOMB_CREATED,
    ROCKET_CREATED,
    DISCO_BALL_CREATED,

    // Ad Events
    AD_SHOWN,
    AD_CLOSED,
    AD_FAILED,
    REWARDED_AD_SHOWN,
    REWARDED_AD_COMPLETED,
    REWARDED_AD_FAILED,
    
    // Sound Events
    SOUND_PLAYED,
    MUSIC_STARTED,
    MUSIC_STOPPED,
    SOUND_SETTINGS_CHANGED,

    // Timer Events
    TIMER_STARTED,
    TIMER_EXPIRED,
    TIMER_PASSED,   
}
